<?php

namespace Tests\Unit;


use App\Manager\UserManager;
use Tests\TestCase;

class UserManagerTest extends TestCase
{
    /**
     * @var \App\Manager\Contract\UserManager
     */
    private $manager;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->manager = $this->app->make(UserManager::class);
    }

    public function testCreate()
    {
        $t = $this->manager->findAll();
    }
}